/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attendence.management.system;

import Classes.Connection2DB;
import java.awt.Color;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;

/**
 *
 * @author AKHIL REJI
 */
public class ConfirmationForm extends javax.swing.JFrame implements WindowListener{

    /**
     * Creates new form ConfirmationForm
     */
    public ConfirmationForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        addWindowListener(this);
          //this.setOpacity(5);
          this.setBackground( new Color(1,22,39,95) );
          getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelname = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonReject = new javax.swing.JButton();
        jButtonAccept = new javax.swing.JButton();

        jLabel6.setBackground(new java.awt.Color(153, 153, 0));
        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("A user named");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(1, 22, 39));

        jLabelname.setBackground(new java.awt.Color(153, 153, 0));
        jLabelname.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabelname.setForeground(new java.awt.Color(255, 255, 255));
        jLabelname.setText("             ");

        jLabel7.setBackground(new java.awt.Color(153, 153, 0));
        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("This person in seeking for your acceptance.Want to accept?");

        jButtonReject.setBackground(new java.awt.Color(242, 38, 19));
        jButtonReject.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonReject.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReject.setText("Reject");
        jButtonReject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRejectMouseClicked(evt);
            }
        });
        jButtonReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRejectActionPerformed(evt);
            }
        });

        jButtonAccept.setBackground(new java.awt.Color(34, 167, 240));
        jButtonAccept.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAccept.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAccept.setText("Accept");
        jButtonAccept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAcceptMouseClicked(evt);
            }
        });
        jButtonAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcceptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jButtonReject, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)
                        .addComponent(jButtonAccept))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabelname, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabelname)
                .addGap(2, 2, 2)
                .addComponent(jLabel7)
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonReject, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRejectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRejectMouseClicked
             // TODO add your handling code here:
           Connection2DB C=new Connection2DB();
        Connection conn=C.setconnection();
        
        String sql;
        String fname=null;
        String lname=null;
         PreparedStatement st;
            int var=0;
         try {
             st = conn.prepareStatement("select * from Login");
              ResultSet rs = st.executeQuery();
              while(rs.next())
              {
                 var=rs.getInt("Verify");
                 if(var<=4)
                 {
                    fname=rs.getString("firstname");
                    lname=rs.getString("lastname");
                    break;
                 }
                 
              }
         } catch (SQLException ex) {
             Logger.getLogger(AboutForm.class.getName()).log(Level.SEVERE, null, ex);
         }
         
         sql="DELETE FROM LOGIN WHERE FIRSTNAME=? AND LASTNAME=?";
            PreparedStatement pst;
        try {
            pst = conn.prepareStatement(sql);
        
            pst.setString(1,fname );
            pst.setString(2,lname );
            
            
            
            pst.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(ConfirmationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
           
             
             AboutForm abtf=new AboutForm();
        abtf.setVisible(true);
        abtf.pack();
        abtf.setLocationRelativeTo(null);//to make center on screen
        abtf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonRejectMouseClicked

    private void jButtonAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcceptActionPerformed

    }//GEN-LAST:event_jButtonAcceptActionPerformed

    private void jButtonRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRejectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRejectActionPerformed

    private void jButtonAcceptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAcceptMouseClicked
        // TODO add your handling code here:
                 Connection2DB C=new Connection2DB();
        Connection conn=C.setconnection();
        
        String sql;
        String fname=null;
        String lname=null;
         PreparedStatement st;
            int var=0;
         try {
             st = conn.prepareStatement("select * from Login");
              ResultSet rs = st.executeQuery();
              while(rs.next())
              {
                 var=rs.getInt("Verify");
                 if(var<=4)
                 {
                    fname=rs.getString("firstname");
                    lname=rs.getString("lastname");
                    break;
                 }
                 
              }
         } catch (SQLException ex) {
             Logger.getLogger(AboutForm.class.getName()).log(Level.SEVERE, null, ex);
         }
              
                     sql="UPDATE LOGIN SET VERIFY=? WHERE FIRSTNAME=? AND LASTNAME=?";
            PreparedStatement pst;
        try {
            pst = conn.prepareStatement(sql);
             pst.setInt(1,5);
            pst.setString(2,fname );
            pst.setString(3,lname );
            
            
            
            pst.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(ConfirmationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
           
              
        
         AboutForm abtf=new AboutForm();
        abtf.setVisible(true);
        abtf.pack();
        abtf.setLocationRelativeTo(null);//to make center on screen
        abtf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_jButtonAcceptMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAccept;
    private javax.swing.JButton jButtonReject;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelname;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
         Connection2DB C=new Connection2DB();
            Connection conn=C.setconnection();
            PreparedStatement st;
            int var;
        try {
            st = conn.prepareStatement("select * from Login");
            ResultSet rs = st.executeQuery();
            while(rs.next())
                    {
                        var=rs.getInt("Verify");
                 if(var<=4)
                 {
                     jLabelname.setText(rs.getString("Firstname")+" "+rs.getString("Lastname"));
                     break;
                 }
                    }
        } catch (SQLException ex) {
            Logger.getLogger(ConfirmationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    @Override
    public void windowClosing(WindowEvent e) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowClosed(WindowEvent e) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowIconified(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowActivated(WindowEvent e) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
