/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attendence.management.system;

import javax.swing.JFrame;
import Classes.Calculation;
import Classes.Connection2DB;
import Classes.DaytoDatelinker;
import Classes.viewrecord;
import java.awt.Color;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author AKHIL REJI
 */
public class DashboardForm extends javax.swing.JFrame implements WindowListener {

    /**
     * Creates new form DashboardForm
     */
    public DashboardForm() {
        initComponents();
        this.setLocationRelativeTo(null);
         addWindowListener(this);
         getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabeloverview1 = new javax.swing.JLabel();
        jComboBoxyear = new javax.swing.JComboBox<>();
        jComboBoxsem = new javax.swing.JComboBox<>();
        jButtongo = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        sub1 = new javax.swing.JLabel();
        sub2 = new javax.swing.JLabel();
        sub3 = new javax.swing.JLabel();
        sub4 = new javax.swing.JLabel();
        sub5 = new javax.swing.JLabel();
        sub6 = new javax.swing.JLabel();
        b2 = new javax.swing.JPanel();
        b1 = new javax.swing.JPanel();
        b3 = new javax.swing.JPanel();
        b4 = new javax.swing.JPanel();
        b5 = new javax.swing.JPanel();
        cover = new javax.swing.JPanel();
        remain = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        covday = new javax.swing.JLabel();
        remday = new javax.swing.JLabel();
        b6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabeloverview = new javax.swing.JLabel();
        jLabelattendance = new javax.swing.JLabel();
        jLabelabout = new javax.swing.JLabel();
        jLabelstudent = new javax.swing.JLabel();
        jLabelsubject = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        minimize = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabellogin = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabelsignout = new javax.swing.JLabel();
        log = new javax.swing.JLabel();
        jLabelattendance3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(1, 22, 39));

        jPanel2.setBackground(new java.awt.Color(220, 220, 220));

        jPanel3.setBackground(new java.awt.Color(1, 22, 39));

        jLabel1.setBackground(new java.awt.Color(1, 22, 39));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(234, 240, 241));
        jLabel1.setText("Dashboard");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(51, 101, 138));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        jPanel4.setLayout(null);

        jPanel13.setBackground(new java.awt.Color(1, 22, 39));

        jLabeloverview1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabeloverview1.setForeground(new java.awt.Color(234, 240, 241));
        jLabeloverview1.setText("Select Class");
        jLabeloverview1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabeloverview1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabeloverview1MouseClicked(evt);
            }
        });

        jComboBoxyear.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jComboBoxyear.setMaximumRowCount(3);
        jComboBoxyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st year", "2nd year", "3ed year" }));
        jComboBoxyear.setToolTipText("");

        jComboBoxsem.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jComboBoxsem.setMaximumRowCount(3);
        jComboBoxsem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st semester", "2nd semester" }));
        jComboBoxsem.setToolTipText("");
        jComboBoxsem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBoxsemMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboBoxsemMouseReleased(evt);
            }
        });

        jButtongo.setBackground(new java.awt.Color(51, 102, 0));
        jButtongo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtongo.setForeground(new java.awt.Color(255, 255, 255));
        jButtongo.setText("Go");
        jButtongo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtongoMouseClicked(evt);
            }
        });
        jButtongo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtongoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabeloverview1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBoxyear, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxsem, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtongo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabeloverview1)
                .addContainerGap(184, Short.MAX_VALUE))
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addGap(0, 82, Short.MAX_VALUE)
                    .addComponent(jComboBoxyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(12, 12, 12)
                    .addComponent(jComboBoxsem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(22, 22, 22)
                    .addComponent(jButtongo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 18, Short.MAX_VALUE)))
        );

        jPanel4.add(jPanel13);
        jPanel13.setBounds(20, 30, 190, 220);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setForeground(new java.awt.Color(0, 0, 0));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel7);
        jPanel7.setBounds(20, 270, 1020, 300);

        sub1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        sub1.setForeground(new java.awt.Color(234, 240, 241));
        sub1.setText("     ");
        sub1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sub1MouseClicked(evt);
            }
        });
        jPanel4.add(sub1);
        sub1.setBounds(240, 50, 150, 25);

        sub2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        sub2.setForeground(new java.awt.Color(234, 240, 241));
        sub2.setText("      ");
        sub2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sub2MouseClicked(evt);
            }
        });
        jPanel4.add(sub2);
        sub2.setBounds(240, 80, 150, 25);

        sub3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        sub3.setForeground(new java.awt.Color(234, 240, 241));
        sub3.setText("      ");
        sub3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sub3MouseClicked(evt);
            }
        });
        jPanel4.add(sub3);
        sub3.setBounds(240, 110, 150, 25);

        sub4.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        sub4.setForeground(new java.awt.Color(234, 240, 241));
        sub4.setText("     ");
        sub4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sub4MouseClicked(evt);
            }
        });
        jPanel4.add(sub4);
        sub4.setBounds(240, 140, 150, 25);

        sub5.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        sub5.setForeground(new java.awt.Color(234, 240, 241));
        sub5.setText("     ");
        sub5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sub5MouseClicked(evt);
            }
        });
        jPanel4.add(sub5);
        sub5.setBounds(240, 170, 150, 25);

        sub6.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        sub6.setForeground(new java.awt.Color(234, 240, 241));
        sub6.setText("      ");
        sub6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sub6MouseClicked(evt);
            }
        });
        jPanel4.add(sub6);
        sub6.setBounds(240, 200, 150, 25);

        javax.swing.GroupLayout b2Layout = new javax.swing.GroupLayout(b2);
        b2.setLayout(b2Layout);
        b2Layout.setHorizontalGroup(
            b2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        b2Layout.setVerticalGroup(
            b2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel4.add(b2);
        b2.setBounds(400, 80, 10, 20);

        javax.swing.GroupLayout b1Layout = new javax.swing.GroupLayout(b1);
        b1.setLayout(b1Layout);
        b1Layout.setHorizontalGroup(
            b1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        b1Layout.setVerticalGroup(
            b1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel4.add(b1);
        b1.setBounds(400, 50, 10, 20);

        javax.swing.GroupLayout b3Layout = new javax.swing.GroupLayout(b3);
        b3.setLayout(b3Layout);
        b3Layout.setHorizontalGroup(
            b3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        b3Layout.setVerticalGroup(
            b3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel4.add(b3);
        b3.setBounds(400, 110, 10, 20);

        javax.swing.GroupLayout b4Layout = new javax.swing.GroupLayout(b4);
        b4.setLayout(b4Layout);
        b4Layout.setHorizontalGroup(
            b4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        b4Layout.setVerticalGroup(
            b4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel4.add(b4);
        b4.setBounds(400, 140, 10, 20);

        javax.swing.GroupLayout b5Layout = new javax.swing.GroupLayout(b5);
        b5.setLayout(b5Layout);
        b5Layout.setHorizontalGroup(
            b5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        b5Layout.setVerticalGroup(
            b5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel4.add(b5);
        b5.setBounds(400, 170, 10, 20);

        cover.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout coverLayout = new javax.swing.GroupLayout(cover);
        cover.setLayout(coverLayout);
        coverLayout.setHorizontalGroup(
            coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        coverLayout.setVerticalGroup(
            coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel4.add(cover);
        cover.setBounds(710, 40, 100, 100);

        remain.setBackground(new java.awt.Color(0, 0, 0));
        remain.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout remainLayout = new javax.swing.GroupLayout(remain);
        remain.setLayout(remainLayout);
        remainLayout.setHorizontalGroup(
            remainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        remainLayout.setVerticalGroup(
            remainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel4.add(remain);
        remain.setBounds(810, 40, 100, 100);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Covered");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(730, 20, 61, 19);

        covday.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        covday.setForeground(new java.awt.Color(0, 0, 0));
        covday.setText("        ");
        jPanel4.add(covday);
        covday.setBounds(710, 210, 100, 19);

        remday.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        remday.setForeground(new java.awt.Color(255, 255, 255));
        remday.setText("       ");
        jPanel4.add(remday);
        remday.setBounds(820, 210, 90, 19);

        javax.swing.GroupLayout b6Layout = new javax.swing.GroupLayout(b6);
        b6.setLayout(b6Layout);
        b6Layout.setHorizontalGroup(
            b6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        b6Layout.setVerticalGroup(
            b6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel4.add(b6);
        b6.setBounds(400, 200, 10, 20);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Remaing");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(820, 20, 61, 19);

        jLabeloverview.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabeloverview.setForeground(new java.awt.Color(234, 240, 241));
        jLabeloverview.setText("Overview     ");
        jLabeloverview.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabeloverview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabeloverviewMouseClicked(evt);
            }
        });

        jLabelattendance.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelattendance.setForeground(new java.awt.Color(234, 240, 241));
        jLabelattendance.setText("Attendance  ");
        jLabelattendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelattendanceMouseClicked(evt);
            }
        });

        jLabelabout.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelabout.setForeground(new java.awt.Color(234, 240, 241));
        jLabelabout.setText("Admin Panel");
        jLabelabout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelaboutMouseClicked(evt);
            }
        });

        jLabelstudent.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelstudent.setForeground(new java.awt.Color(234, 240, 241));
        jLabelstudent.setText("Student       ");
        jLabelstudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelstudentMouseClicked(evt);
            }
        });

        jLabelsubject.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelsubject.setForeground(new java.awt.Color(234, 240, 241));
        jLabelsubject.setText("Subject       ");
        jLabelsubject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelsubjectMouseClicked(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 159, 28));

        minimize.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        minimize.setForeground(new java.awt.Color(234, 240, 241));
        minimize.setText("-");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });

        exit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(234, 240, 241));
        exit.setText("x");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimize)
                .addGap(3, 3, 3)
                .addComponent(exit)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minimize)
                    .addComponent(exit)))
        );

        jPanel8.setBackground(new java.awt.Color(0, 102, 0));

        jLabellogin.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabellogin.setForeground(new java.awt.Color(234, 240, 241));
        jLabellogin.setText("      ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabellogin, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabellogin, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel9.setBackground(new java.awt.Color(153, 0, 0));

        jLabelsignout.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelsignout.setForeground(new java.awt.Color(234, 240, 241));
        jLabelsignout.setText("Logout");
        jLabelsignout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelsignoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelsignout)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelsignout, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        log.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        log.setForeground(new java.awt.Color(234, 240, 241));
        log.setText("   ");
        log.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logMouseClicked(evt);
            }
        });

        jLabelattendance3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabelattendance3.setForeground(new java.awt.Color(234, 240, 241));
        jLabelattendance3.setText("Login as");
        jLabelattendance3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelattendance3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelattendance)
                                    .addComponent(jLabeloverview)
                                    .addComponent(jLabelstudent)
                                    .addComponent(jLabelsubject)
                                    .addComponent(jLabelabout)))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelattendance3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1047, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabeloverview)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelattendance)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelstudent)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelsubject)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelabout)
                        .addGap(42, 42, 42)
                        .addComponent(jLabelattendance3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(log)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabeloverviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeloverviewMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabeloverviewMouseClicked

    private void jLabelattendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelattendanceMouseClicked
        // TODO add your handling code here:
        AttendanceForm af=new AttendanceForm();
        af.setVisible(true);
        af.pack();
        af.setLocationRelativeTo(null);//to make center on screen
        af.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelattendanceMouseClicked

    private void jLabelstudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelstudentMouseClicked
        // TODO add your handling code here:
        StudentForm stdf=new StudentForm();
        stdf.setVisible(true);
        stdf.pack();
        stdf.setLocationRelativeTo(null);//to make center on screen
        stdf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelstudentMouseClicked

    private void jLabelsubjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsubjectMouseClicked
        // TODO add your handling code here:
        SubjectForm subf=new SubjectForm();
        subf.setVisible(true);
        subf.pack();
        subf.setLocationRelativeTo(null);//to make center on screen
        subf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelsubjectMouseClicked

    private void jLabelaboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelaboutMouseClicked
        // TODO add your handling code here:
       Connection2DB C=new Connection2DB();
            Connection conn=C.setconnection();
            PreparedStatement st;
            int var=0;
         try {
             st = conn.prepareStatement("select * from Login");
              ResultSet rs = st.executeQuery();
              while(rs.next())
              {
                 var=rs.getInt("Verify");
                 if(var==7 && rs.getString("Login").equals("in"))
                 {
                     AboutForm abtf=new AboutForm();
        abtf.setVisible(true);
        abtf.pack();
        abtf.setLocationRelativeTo(null);//to make center on screen
        abtf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        break;
                 }
                 else
                 {
                     JOptionPane.showMessageDialog(null,"You're not autharised to acces this space!","Denied",JOptionPane.ERROR_MESSAGE );
                     break;
                 }
                 
              }
         } catch (SQLException ex) {
             Logger.getLogger(AboutForm.class.getName()).log(Level.SEVERE, null, ex);
         }
           
        
       
    }//GEN-LAST:event_jLabelaboutMouseClicked

    private void jLabelsignoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsignoutMouseClicked
        // TODO add your handling code here:
        LogoutForm ltf=new LogoutForm();
        ltf.setVisible(true);
        ltf.pack();
        ltf.setLocationRelativeTo(null);//to make center on screen
        ltf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
    }//GEN-LAST:event_jLabelsignoutMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
 LogoutForm ltf=new LogoutForm();
        ltf.setVisible(true);
        ltf.pack();
        ltf.setLocationRelativeTo(null);//to make center on screen
        ltf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_exitMouseClicked

    private void jLabeloverview1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeloverview1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabeloverview1MouseClicked

    private void jComboBoxsemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxsemMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxsemMouseExited

    private void jComboBoxsemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxsemMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxsemMouseReleased

    private void jButtongoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtongoMouseClicked
        String year=(String) jComboBoxyear.getSelectedItem();
        String sem=(String) jComboBoxsem.getSelectedItem();
        Calculation cal=new Calculation();
        viewrecord vr=new viewrecord();
        jPanel7.setVisible(true);
        b1.setSize(1, 20);
         b2.setSize(1, 20);
         b3.setSize(1, 20);
         b4.setSize(1, 20);
         b5.setSize(1, 20);
         
         
         sub1.setText("");
         sub2.setText("");
         sub3.setText("");
         sub4.setText("");
         sub5.setText("");
         sub6.setText("");
         
        int t1=0;
        int t2=0;
        int t3=0;
        int t4=0;
        int t5=0;
        int t6=0;
        
        
        int ta1=0;
        int ta2=0;
        int ta3=0;
        int ta4=0;
        int ta5=0;
        int ta6=0;
        
        int a = 0;
        int b =100;
        try {
            cal.classcalc();
        } catch (SQLException ex) {
            Logger.getLogger(DashboardForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        cal.studentcalc();
        cal.subjectcal();
        
        {
        int sum=0;
        int no=0;
        int avg=0;
        int log=0;
        String flag=null;
        Connection2DB C=new Connection2DB();
        Connection conn=C.setconnection();
        PreparedStatement st=null;
             
        if(year.equals("1st year"))
        {
            if(sem.equals("1st semester"))
            {
                flag="11";
                try {
                    vr.tab1(jTable1);
                   
        
        st = conn.prepareStatement("select * from subject where year = ? and  semester= ?  ");
        st.setString(1, "1st year");  
        st.setString(2, "1st semester"); 
    
    ResultSet rs = st.executeQuery();
                } catch (SQLException ex) {
                    Logger.getLogger(DashboardForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else
            {
                flag="12";
                 try {
                    vr.tab2(jTable1);
                } catch (SQLException ex) {
                    Logger.getLogger(DashboardForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        if(year.equals("2ndd year"))
        {
         if(sem.equals("1st semester"))
            {
                flag="21";
                 try {
                    vr.tab3(jTable1);
                } catch (SQLException ex) {
                    Logger.getLogger(DashboardForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else
            {
                flag="22";
                 try {
                    vr.tab4(jTable1);
                } catch (SQLException ex) {
                    Logger.getLogger(DashboardForm.class.getName()).log(Level.SEVERE, null, ex);
                }
               
            }
                
        }
       
         if(year.equals("3ed year"))
        {
         if(sem.equals("1st semester"))
            {
                flag="31";
                 try {
                    vr.tab5(jTable1);
                } catch (SQLException ex) {
                    Logger.getLogger(DashboardForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else
            {
                flag="32";
                 try {
                    vr.tab6(jTable1);
                } catch (SQLException ex) {
                    Logger.getLogger(DashboardForm.class.getName()).log(Level.SEVERE, null, ex);
                }
               
            }
                
        }
         ResultSet rst=null;
         String sql=null;
         PreparedStatement pstt=null;
         
         try {
             switch(flag)
             {
                case "11": sql="select * from Subject where year=? and semester=?";
                pstt=conn.prepareStatement(sql);
                pstt.setString(1, "1st year");
                pstt.setString(2, "1st semester");
                rst = pstt.executeQuery();
               
                           break; 
                 case "12":sql="select * from Subject where year=? and semester=?";
                pstt=conn.prepareStatement(sql);
                pstt.setString(1, "1st year");
                pstt.setString(2, "2nd semester");
                rst = pstt.executeQuery();
                           break;
                 case "21":sql="select * from Subject where year=? and semester=?";
                pstt=conn.prepareStatement(sql);
                pstt.setString(1, "2nd year");
                pstt.setString(2, "1st semester");
                rst = pstt.executeQuery();
                           break;
                 case "22": sql="select * from Subject where year=? and semester=?";
                pstt=conn.prepareStatement(sql);
                pstt.setString(1,  "2nd year");
                pstt.setString(2, "2nd semester");
                rst = pstt.executeQuery();
                           break;
                 case "31":sql="select * from Subject where year=? and semester=?";
                pstt=conn.prepareStatement(sql);
                pstt.setString(1, "3eed year");
                pstt.setString(2, "1st semester");
                rst = pstt.executeQuery();
                           break;
                 case "32": sql="select * from Subject where year=? and semester?";
                pstt=conn.prepareStatement(sql);
                pstt.setString(1, "3ed year");
                pstt.setString(2, "2nd semester");
                rst = pstt.executeQuery();
                            break;
                 default:   break;       
             }   int f=1;
              
               while(rst.next())
               {
                   if(rst.getString("id").equals("1"))
                   {
                       sub1.setText(rst.getString("Subject"));  
                   }
                   else
                       if(rst.getString("id").equals("2"))
                               {
                                 sub2.setText(rst.getString("Subject")); 
                               }
                   
                   else
                       if(rst.getString("id").equals("3"))
                               {
                                  sub3.setText(rst.getString("Subject")); 
                               }
                   
                   else
                       if(rst.getString("id").equals("4"))
                               {
                                  sub4.setText(rst.getString("Subject"));  
                               }
                   
                   else
                       if(rst.getString("id").equals("5"))
                               {
                                  sub5.setText(rst.getString("Subject"));  
                               }
                   
                   else
                       if(rst.getString("id").equals("6"))
                               {
                                  sub6.setText(rst.getString("Subject")); 
                               }
                   
                 
                   
               }
              
         }  catch (SQLException ex) {
             
                Logger.getLogger(DashboardForm.class.getName()).log(Level.SEVERE, null, ex);
            }
          
         ResultSet rs=null;
         try {
                st = conn.prepareStatement("select * from attendance"+flag);
                rs = st.executeQuery();
                while(rs.next())
          {
              
          log=rs.getInt("Class");
          sum=sum+log;
          
          
         
          if(a==0)
          {
          a=rs.getInt("flag");
         
          b=100-a;
          }
         
          t1=t1+rs.getInt("subject1");
          t2=t2+rs.getInt("subject2");
          t3=t3+rs.getInt("subject3");
          t4=t4+rs.getInt("subject4");
          t5=t5+rs.getInt("subject5");
          t6=t6+rs.getInt("subject6");
          no++;
          }
            avg=sum/no; 
            ta1=t1/no;
            ta2=t2/no;
            ta3=t3/no;
            ta4=t4/no;
            ta5=t5/no;
            ta6=t6/no;
       
         } catch (SQLException ex) {
                Logger.getLogger(DashboardForm.class.getName()).log(Level.SEVERE, null, ex);
            }
         b1.setSize(ta1*3, 20);
         b2.setSize(ta2*3, 20);
         b3.setSize(ta3*3, 20);
         b4.setSize(ta4*3, 20);
         b5.setSize(ta5*3, 20);
         b6.setSize(ta6*3, 20);
         b1.setVisible(true);
         b2.setVisible(true);
         b3.setVisible(true);
         b4.setVisible(true);
         b5.setVisible(true);
         b6.setVisible(true);
        cover.setSize(100, a);
         remain.setSize(100,b);
         covday.setText(a+" Day(s)");
         remday.setText(b+" Day(s)");
         
        }
       
        
        
       
       
         
        
    }//GEN-LAST:event_jButtongoMouseClicked
    
    private void jButtongoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtongoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtongoActionPerformed

    private void logMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logMouseClicked

    private void sub1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sub1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sub1MouseClicked

    private void sub2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sub2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sub2MouseClicked

    private void sub3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sub3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sub3MouseClicked

    private void sub4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sub4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sub4MouseClicked

    private void sub5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sub5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sub5MouseClicked

    private void sub6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sub6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sub6MouseClicked

    private void jLabelattendance3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelattendance3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelattendance3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel b1;
    private javax.swing.JPanel b2;
    private javax.swing.JPanel b3;
    private javax.swing.JPanel b4;
    private javax.swing.JPanel b5;
    private javax.swing.JPanel b6;
    private javax.swing.JLabel covday;
    private javax.swing.JPanel cover;
    private javax.swing.JLabel exit;
    private javax.swing.JButton jButtongo;
    private javax.swing.JComboBox<String> jComboBoxsem;
    private javax.swing.JComboBox<String> jComboBoxyear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelabout;
    private javax.swing.JLabel jLabelattendance;
    private javax.swing.JLabel jLabelattendance3;
    private javax.swing.JLabel jLabellogin;
    private javax.swing.JLabel jLabeloverview;
    private javax.swing.JLabel jLabeloverview1;
    private javax.swing.JLabel jLabelsignout;
    private javax.swing.JLabel jLabelstudent;
    private javax.swing.JLabel jLabelsubject;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel log;
    private javax.swing.JLabel minimize;
    private javax.swing.JPanel remain;
    private javax.swing.JLabel remday;
    private javax.swing.JLabel sub1;
    private javax.swing.JLabel sub2;
    private javax.swing.JLabel sub3;
    private javax.swing.JLabel sub4;
    private javax.swing.JLabel sub5;
    private javax.swing.JLabel sub6;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent e) {
        Connection2DB C=new Connection2DB();
        
        Connection conn=C.setconnection();
        PreparedStatement st;    
        ResultSet rs=null;
        
        try {
            st = conn.prepareStatement("select * from login where login=? ");
            st.setString(1, "in");  
        
            rs = st.executeQuery(); 
            while(rs.next())
            {
             jLabellogin.setText(rs.getString("Firstname"));
             log.setText(rs.getString("last_login"));
              
            }
            DaytoDatelinker dt=new DaytoDatelinker();
            dt.sem1();
            String sql;
                     sql="UPDATE LOGIN SET last_login=? WHERE  login=?";
            PreparedStatement pst=conn.prepareStatement(sql);
            java.util.Date date=null;
                    
                   date =new java.util.Date();  
            //pst.setDate(1, (java.sql.Date) date);
            SimpleDateFormat sdf=new SimpleDateFormat();
            String dates=sdf.format(date);
            pst.setString(1,dates);
            pst.setString(2,"in");
           
            pst.executeUpdate();
            
        } catch (SQLException ex) {
            Logger.getLogger(DashboardForm.class.getName()).log(Level.SEVERE, null, ex);
        }
       
         b1.setSize(1, 20);
         b2.setSize(1, 20);
         b3.setSize(1, 20);
         b4.setSize(1, 20);
         b5.setSize(1, 20);
         b6.setSize(1, 20);
         b1.hide();
         b2.hide();
         b3.hide();
         b4.hide();
         b5.hide();
         b6.hide();
          
       
       jPanel7.hide();
    }

    @Override
    public void windowClosing(WindowEvent e) {
       
    }

    @Override
    public void windowClosed(WindowEvent e) {
    }

    @Override
    public void windowIconified(WindowEvent e) {
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
    }

    @Override
    public void windowActivated(WindowEvent e) {
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
    }
}
