/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attendence.management.system;
import Classes.viewrecord;
import Classes.Connection2DB;
import javax.swing.JFrame;
import java.awt.*;
import static java.awt.PageAttributes.MediaType.C;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;


/**
 *
 * @author AKHIL REJI
 */
public class SubjectForm extends javax.swing.JFrame implements WindowListener {

    /**
     * Creates new form SubjectForm
     */
    public SubjectForm() {
        initComponents();
          this.setLocationRelativeTo(null);
          jTextFieldidno.setEditable(false);
          addWindowListener(this);
          getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jComboBoxsem = new javax.swing.JComboBox<>();
        jComboBoxyear = new javax.swing.JComboBox<>();
        jLabelabout1 = new javax.swing.JLabel();
        jLabelabout2 = new javax.swing.JLabel();
        jButtongo = new javax.swing.JButton();
        jButtonadd = new javax.swing.JButton();
        jButtonupdate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 2), new java.awt.Dimension(0, 2), new java.awt.Dimension(32767, 2));
        jPanel6 = new javax.swing.JPanel();
        jTextFieldcode = new javax.swing.JTextField();
        jTextFieldno = new javax.swing.JTextField();
        jTextFieldsub = new javax.swing.JTextField();
        jTextFieldidno = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButtondelete = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxsub = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabeloverview = new javax.swing.JLabel();
        jLabelattendance = new javax.swing.JLabel();
        jLabelabout = new javax.swing.JLabel();
        jLabelstudent = new javax.swing.JLabel();
        jLabelsubject = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        minimize = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabelsignout = new javax.swing.JLabel();
        jLabelattendance3 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabellogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(1, 22, 39));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 640));

        jPanel2.setBackground(new java.awt.Color(220, 220, 220));

        jPanel3.setBackground(new java.awt.Color(1, 22, 39));

        jLabel1.setBackground(new java.awt.Color(43, 45, 66));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(234, 240, 241));
        jLabel1.setText("Dashboard");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(51, 101, 138));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        jPanel4.setLayout(null);

        jComboBoxsem.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jComboBoxsem.setMaximumRowCount(3);
        jComboBoxsem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st semester", "2nd semester" }));
        jComboBoxsem.setToolTipText("");
        jPanel4.add(jComboBoxsem);
        jComboBoxsem.setBounds(390, 30, 140, 30);

        jComboBoxyear.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jComboBoxyear.setMaximumRowCount(3);
        jComboBoxyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st year", "2nd year", "3ed year" }));
        jComboBoxyear.setToolTipText("");
        jPanel4.add(jComboBoxyear);
        jComboBoxyear.setBounds(110, 30, 140, 30);

        jLabelabout1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelabout1.setForeground(new java.awt.Color(234, 240, 241));
        jLabelabout1.setText("Semester");
        jLabelabout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelabout1MouseClicked(evt);
            }
        });
        jPanel4.add(jLabelabout1);
        jLabelabout1.setBounds(270, 30, 90, 24);

        jLabelabout2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelabout2.setForeground(new java.awt.Color(234, 240, 241));
        jLabelabout2.setText("Year");
        jLabelabout2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelabout2MouseClicked(evt);
            }
        });
        jPanel4.add(jLabelabout2);
        jLabelabout2.setBounds(50, 30, 38, 24);

        jButtongo.setBackground(new java.awt.Color(51, 102, 0));
        jButtongo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtongo.setForeground(new java.awt.Color(255, 255, 255));
        jButtongo.setText("Go");
        jButtongo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtongoMouseClicked(evt);
            }
        });
        jButtongo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtongoActionPerformed(evt);
            }
        });
        jPanel4.add(jButtongo);
        jButtongo.setBounds(580, 30, 100, 27);

        jButtonadd.setBackground(new java.awt.Color(0, 102, 255));
        jButtonadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonadd.setForeground(new java.awt.Color(255, 255, 255));
        jButtonadd.setText("Add");
        jButtonadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonaddMouseClicked(evt);
            }
        });
        jButtonadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaddActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonadd);
        jButtonadd.setBounds(150, 500, 100, 27);

        jButtonupdate.setBackground(new java.awt.Color(0, 102, 255));
        jButtonupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonupdate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonupdate.setText("Update");
        jButtonupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonupdateMouseClicked(evt);
            }
        });
        jButtonupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonupdateActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonupdate);
        jButtonupdate.setBounds(300, 500, 100, 27);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(234, 240, 241));
        jLabel6.setText("Subject code:");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(60, 380, 120, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(234, 240, 241));
        jLabel8.setText("Subject:");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(100, 420, 80, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(234, 240, 241));
        jLabel9.setText("Enroll no:");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(90, 460, 90, 22);
        jPanel4.add(filler1);
        filler1.setBounds(0, 0, 0, 2);

        jPanel6.setBackground(new java.awt.Color(1, 22, 39));

        jTextFieldcode.setBackground(new java.awt.Color(191, 191, 191));
        jTextFieldcode.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldcode.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldcode.setBorder(null);
        jTextFieldcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldcodeActionPerformed(evt);
            }
        });

        jTextFieldno.setBackground(new java.awt.Color(191, 191, 191));
        jTextFieldno.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldno.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldno.setBorder(null);
        jTextFieldno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnoActionPerformed(evt);
            }
        });

        jTextFieldsub.setBackground(new java.awt.Color(191, 191, 191));
        jTextFieldsub.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldsub.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldsub.setBorder(null);
        jTextFieldsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldsubActionPerformed(evt);
            }
        });

        jTextFieldidno.setBackground(new java.awt.Color(191, 191, 191));
        jTextFieldidno.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldidno.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldidno.setBorder(null);
        jTextFieldidno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldidnoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(234, 240, 241));
        jLabel11.setText("No:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldidno, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldsub, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldno, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldcode, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldidno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldcode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldsub, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        jPanel4.add(jPanel6);
        jPanel6.setBounds(30, 310, 460, 240);

        jPanel7.setBackground(new java.awt.Color(1, 22, 39));

        jButtondelete.setBackground(new java.awt.Color(242, 38, 19));
        jButtondelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtondelete.setForeground(new java.awt.Color(255, 255, 255));
        jButtondelete.setText("Delete");
        jButtondelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtondeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtondeleteMouseEntered(evt);
            }
        });
        jButtondelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondeleteActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(234, 240, 241));
        jLabel10.setText("Select Subject");

        jComboBoxsub.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jComboBoxsub.setMaximumRowCount(3);
        jComboBoxsub.setToolTipText("");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtondelete, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxsub, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBoxsub, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jButtondelete)
                .addGap(40, 40, 40))
        );

        jPanel4.add(jPanel7);
        jPanel7.setBounds(620, 350, 390, 200);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setForeground(new java.awt.Color(0, 0, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel8);
        jPanel8.setBounds(10, 70, 1080, 200);

        jLabeloverview.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabeloverview.setForeground(new java.awt.Color(234, 240, 241));
        jLabeloverview.setText("Overview     ");
        jLabeloverview.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabeloverview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabeloverviewMouseClicked(evt);
            }
        });

        jLabelattendance.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelattendance.setForeground(new java.awt.Color(234, 240, 241));
        jLabelattendance.setText("Attendance  ");
        jLabelattendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelattendanceMouseClicked(evt);
            }
        });

        jLabelabout.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelabout.setForeground(new java.awt.Color(234, 240, 241));
        jLabelabout.setText("Admin Panel");
        jLabelabout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelaboutMouseClicked(evt);
            }
        });

        jLabelstudent.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelstudent.setForeground(new java.awt.Color(234, 240, 241));
        jLabelstudent.setText("Student       ");
        jLabelstudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelstudentMouseClicked(evt);
            }
        });

        jLabelsubject.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelsubject.setForeground(new java.awt.Color(234, 240, 241));
        jLabelsubject.setText("Subject       ");

        jPanel5.setBackground(new java.awt.Color(255, 159, 28));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        minimize.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        minimize.setForeground(new java.awt.Color(234, 240, 241));
        minimize.setText("-");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });

        exit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(234, 240, 241));
        exit.setText("x");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimize)
                .addGap(3, 3, 3)
                .addComponent(exit)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minimize)
                    .addComponent(exit)))
        );

        jPanel9.setBackground(new java.awt.Color(153, 0, 0));

        jLabelsignout.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelsignout.setForeground(new java.awt.Color(234, 240, 241));
        jLabelsignout.setText("Logout");
        jLabelsignout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelsignoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelsignout)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelsignout, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jLabelattendance3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabelattendance3.setForeground(new java.awt.Color(234, 240, 241));
        jLabelattendance3.setText("Login as");
        jLabelattendance3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelattendance3MouseClicked(evt);
            }
        });

        jPanel11.setBackground(new java.awt.Color(0, 102, 0));

        jLabellogin.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabellogin.setForeground(new java.awt.Color(234, 240, 241));
        jLabellogin.setText("      ");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabellogin, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabellogin, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelattendance)
                            .addComponent(jLabeloverview)
                            .addComponent(jLabelstudent)
                            .addComponent(jLabelsubject)
                            .addComponent(jLabelabout)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelattendance3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1101, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabeloverview)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelattendance)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelstudent)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelsubject)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelabout)
                        .addGap(80, 80, 80)
                        .addComponent(jLabelattendance3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
 LogoutForm ltf=new LogoutForm();
        ltf.setVisible(true);
        ltf.pack();
        ltf.setLocationRelativeTo(null);//to make center on screen
        ltf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }//GEN-LAST:event_exitMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void jLabelattendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelattendanceMouseClicked
        // TODO add your handling code here:
         AttendanceForm af=new AttendanceForm();
        af.setVisible(true);
        af.pack();
        af.setLocationRelativeTo(null);//to make center on screen
        af.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelattendanceMouseClicked

    private void jLabelstudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelstudentMouseClicked
        // TODO add your handling code here:
         StudentForm stdf=new StudentForm();
        stdf.setVisible(true);
        stdf.pack();
        stdf.setLocationRelativeTo(null);//to make center on screen
        stdf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelstudentMouseClicked

    private void jLabelaboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelaboutMouseClicked
Connection2DB C=new Connection2DB();
            Connection conn=C.setconnection();
            PreparedStatement st;
            int var=0;
         try {
             st = conn.prepareStatement("select * from Login");
              ResultSet rs = st.executeQuery();
              while(rs.next())
              {
                 var=rs.getInt("Verify");
                 if(var==7)
                 {
                     AboutForm abtf=new AboutForm();
        abtf.setVisible(true);
        abtf.pack();
        abtf.setLocationRelativeTo(null);//to make center on screen
        abtf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        break;
                 }
                 else
                 {
                     JOptionPane.showMessageDialog(null,"You're not autharised to acces this space!","Denied",JOptionPane.ERROR_MESSAGE );
                     break;
                 }
                 
              }
         } catch (SQLException ex) {
             Logger.getLogger(AboutForm.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jLabelaboutMouseClicked

    private void jLabeloverviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeloverviewMouseClicked
        // TODO add your handling code here:
         DashboardForm dbf=new DashboardForm();
        dbf.setVisible(true);
        dbf.pack();
        dbf.setLocationRelativeTo(null);//to make center on screen
        dbf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabeloverviewMouseClicked

    private void jLabelabout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelabout1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelabout1MouseClicked

    private void jLabelabout2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelabout2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelabout2MouseClicked

    private void jButtondeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtondeleteMouseClicked
        
        Connection2DB C=new Connection2DB();
        Connection con=C.setconnection();
        
        
        try {
           
            String sql="delete from subject where subject= ?";
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1, (String) jComboBoxsub.getSelectedItem());
                
                     
            pst.executeUpdate();
                                
            JOptionPane.showMessageDialog(null, "Subject Deleted");
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        {
            viewrecord vr=new viewrecord();
             if(jComboBoxyear.getSelectedItem().equals("1st year"))
       {
           if(jComboBoxsem.getSelectedItem().equals("1st semester"))
           {
        
        try {
            vr.view1(jTable1);
     
    
        
    
            
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         
           }
           else
           {
               try {
            vr.view2(jTable1);
            
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
               
           }
           
       }
       if(jComboBoxyear.getSelectedItem().equals("2nd year"))
       {
           if(jComboBoxsem.getSelectedItem().equals("1st semester"))
           {
       
        try {
            vr.view3(jTable1);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
           }
           else
           {
               try {
            vr.view4(jTable1);
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
               
           }
           
       }
       if(jComboBoxyear.getSelectedItem().equals("3ed year"))
       {
           if(jComboBoxsem.getSelectedItem().equals("1st semester"))
           {
       
        try {
            vr.view5(jTable1);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
           }
           else
           {
               try {
            vr.view6(jTable1);
           
            
            
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
               
           }
           
       }
            
            
        }
            
        jTable1.validate();
       
        
        
        
        
        
    }//GEN-LAST:event_jButtondeleteMouseClicked

    private void jButtondeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondeleteActionPerformed
        
        Connection2DB C=new Connection2DB();
        Connection conn=C.setconnection();
        PreparedStatement st = null;    
        
        
        try {
            st = conn.prepareStatement("delete from subject where subject = ?");
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {  
            st.setString(1, (String) jComboBoxsub.getSelectedItem());
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
        try {
            st.execute();
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jButtondeleteActionPerformed

    private void jButtongoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtongoMouseClicked
       viewrecord vr=new viewrecord();
       Connection2DB C=new Connection2DB();
       String flag="1";
       int maxID = 1;
       Connection con=C.setconnection();
       Statement s2 = null;

        try {
            s2 = con.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       if(jComboBoxyear.getSelectedItem().equals("1st year"))
       {
           if(jComboBoxsem.getSelectedItem().equals("1st semester"))
           {
       
        try {
            vr.view1(jTable1);
            
            Connection conn=C.setconnection();
        PreparedStatement st,pst;    
        
        st = conn.prepareStatement("select * from subject where year = ? and  semester= ?  ");
        st.setString(1, "1st year");  
        st.setString(2, "1st semester"); 
    
        ResultSet rs = st.executeQuery();
    
        
                
    
    jComboBoxsub.removeAllItems();
    while(rs.next())
    {
        maxID++;
        String sub=rs.getString("SUBJECT");
        jComboBoxsub.addItem(sub);
        
        
                
    }
    
        
    
            
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         
           }
           else
           {
               try {
            vr.view2(jTable1);
            
            Connection conn=C.setconnection();
        PreparedStatement st;    
        
        st = conn.prepareStatement("select * from subject where year = ? and  semester= ?  ");
        st.setString(1, "1st year");  
        st.setString(2, "2nd semester"); 
    
    ResultSet rs = st.executeQuery();
    jComboBoxsub.removeAllItems();
    while(rs.next())
    {
        maxID++;
        String sub=rs.getString("SUBJECT");
        jComboBoxsub.addItem(sub);
        
                
    }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
               
           }
           
       }
       if(jComboBoxyear.getSelectedItem().equals("2nd year"))
       {
           if(jComboBoxsem.getSelectedItem().equals("1st semester"))
           {
       
        try {
            vr.view3(jTable1);
            
            
            Connection conn=C.setconnection();
        PreparedStatement st;    
        
        st = conn.prepareStatement("select * from subject where year = ? and  semester= ?  ");
        st.setString(1, "2nd year");  
        st.setString(2, "1st semester"); 
    
    ResultSet rs = st.executeQuery();
    jComboBoxsub.removeAllItems();
    while(rs.next())
    {
        maxID++;
        String sub=rs.getString("SUBJECT");
        jComboBoxsub.addItem(sub);
        
                
    }
            
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
           }
           else
           {
               try {
            vr.view4(jTable1);
            
            
            Connection conn=C.setconnection();
        PreparedStatement st;    
        
        st = conn.prepareStatement("select * from subject where year = ? and  semester= ?  ");
        st.setString(1, "2nd year");  
        st.setString(2, "2nd semester"); 
    
    ResultSet rs = st.executeQuery();
    jComboBoxsub.removeAllItems();
    while(rs.next())
    {
        maxID++;
        String sub=rs.getString("SUBJECT");
        jComboBoxsub.addItem(sub);
        
                
    }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
               
           }
           
       }
       if(jComboBoxyear.getSelectedItem().equals("3ed year"))
       {
           if(jComboBoxsem.getSelectedItem().equals("1st semester"))
           {
       
        try {
            vr.view5(jTable1);
            
            
            Connection conn=C.setconnection();
        PreparedStatement st;    
        
        st = conn.prepareStatement("select * from subject where year = ? and  semester= ?  ");
        st.setString(1, "3ed year");  
        st.setString(2, "1st semester"); 
    
    ResultSet rs = st.executeQuery();
    jComboBoxsub.removeAllItems();
    while(rs.next())
    {
        maxID++;
        String sub=rs.getString("SUBJECT");
        jComboBoxsub.addItem(sub);
        
                
    }
            
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
           }
           else
           {
               try {
            vr.view6(jTable1);
            
            
            Connection conn=C.setconnection();
        PreparedStatement st;    
        
        st = conn.prepareStatement("select * from subject where year = ? and  semester= ?  ");
        st.setString(1, "3ed year");  
        st.setString(2, "2nd semester"); 
    
    ResultSet rs = st.executeQuery();
    jComboBoxsub.removeAllItems();
    while(rs.next())
    {
        maxID++;
        String sub=rs.getString("SUBJECT");
        jComboBoxsub.addItem(sub);
        
                
    }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
               
           }
           
       }
       switch(maxID)
       {
           case 1:
               jTextFieldidno.setText("1");
               break;
           
           case 2:
               jTextFieldidno.setText("2");
               break;  
           
           case 3:
               jTextFieldidno.setText("3");
               break;
           
           case 4:
               jTextFieldidno.setText("4");
               break;  
           
           case 5:
               jTextFieldidno.setText("5");
               break;
           
           case 6:
               jTextFieldidno.setText("6");
               break;
           
           default:
               jTextFieldidno.setText("7");
               break;    
       }
       
           

        
    }//GEN-LAST:event_jButtongoMouseClicked

    private void jButtongoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtongoActionPerformed
      

        
    }//GEN-LAST:event_jButtongoActionPerformed

    private void jButtonaddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonaddMouseClicked
        Connection2DB C=new Connection2DB();
        Connection conn=C.setconnection();
        Statement st=null;
        String idno=jTextFieldidno.getText();
        String id=jTextFieldcode.getText();
        String sub=jTextFieldsub.getText();
        String no=jTextFieldno.getText();
        String year=(String) jComboBoxyear.getSelectedItem();
        String sem=(String) jComboBoxsem.getSelectedItem();
        int log=1;
        int logs=0;
        
        
        try {
            st =(Statement)conn.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
            
             
           
        ResultSet rs=null;
        try {
            rs=st.executeQuery("SELECT * FROM SUBJECT");
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            while(rs.next())
            {
               
                if ( rs.getString("SUBJECT").equals(sub) || rs.getString("SUBJECT_CODE").equals(id))
                
                {
                    logs=1;
                    break;
                    
                }
                else
                {
                    
                 
                 log=1;   
                }
                
            }
            if (logs==1)
            {
                log=0;
                JOptionPane.showMessageDialog(null,"Subject Already Exist","Can not add",JOptionPane.ERROR_MESSAGE );
                
            }
            if (log==1)
            {
                switch(jTextFieldidno.getText())
                {
                    case "1":
                    case "2":
                    case "3":
                    case "4":
                    case "5":
                    case "6": String sql;
                     sql="INSERT INTO SUBJECT(ID,SUBJECT_CODE,SUBJECT,ENROLL_NO,YEAR,SEMESTER)VALUES(?,?,?,?,?,?)";
            PreparedStatement pstt=conn.prepareStatement(sql);
            pstt.setString(1, idno);
            pstt.setString(2, id);
            pstt.setString(3,sub);
            pstt.setString(4,no );
            pstt.setString(5,year);
            pstt.setString(6,sem);
            pstt.executeUpdate();
            JOptionPane.showMessageDialog(null,"Subject added","Successfull",JOptionPane.INFORMATION_MESSAGE );
            jTextFieldidno.setText("");
            jTextFieldcode.setText("");
            jTextFieldsub.setText("");
            jTextFieldno.setText("");
            viewrecord vr=new viewrecord();
       
       String flag="1";
       int maxID = 1;
       Connection con=C.setconnection();
       Statement s2 = null;

        try {
            s2 = con.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
       PreparedStatement stt,pst;  
       if(jComboBoxyear.getSelectedItem().equals("1st year"))
       {
           if(jComboBoxsem.getSelectedItem().equals("1st semester"))
           {
       
        try {
            vr.view1(jTable1);
            
            
          
        
        stt = conn.prepareStatement("select * from subject where year = ? and  semester= ?  ");
        stt.setString(1, "1st year");  
        stt.setString(2, "1st semester"); 
    
        ResultSet rst = stt.executeQuery();
    
        
                
    
    jComboBoxsub.removeAllItems();
    while(rst.next())
    {
        maxID++;
        String subj=rst.getString("SUBJECT");
        jComboBoxsub.addItem(subj);
        
        
                
    }
    
        
    
            
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         
           }
           else
           {
               try {
            vr.view2(jTable1);
            
              
        
        stt = conn.prepareStatement("select * from subject where year = ? and  semester= ?  ");
        stt.setString(1, "1st year");  
        stt.setString(2, "2nd semester"); 
    
    ResultSet rst = stt.executeQuery();
    jComboBoxsub.removeAllItems();
    while(rst.next())
    {
        maxID++;
        String subj=rst.getString("SUBJECT");
        jComboBoxsub.addItem(subj);
        
                
    }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
               
           }
           
       }
       if(jComboBoxyear.getSelectedItem().equals("2nd year"))
       {
           if(jComboBoxsem.getSelectedItem().equals("1st semester"))
           {
       
        try {
            vr.view3(jTable1);
            
            
            
        
        stt = conn.prepareStatement("select * from subject where year = ? and  semester= ?  ");
        stt.setString(1, "2nd year");  
        stt.setString(2, "1st semester"); 
    
    ResultSet rst = stt.executeQuery();
    jComboBoxsub.removeAllItems();
    while(rst.next())
    {
        maxID++;
        String subj=rst.getString("SUBJECT");
        jComboBoxsub.addItem(subj);
        
                
    }
            
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
           }
           else
           {
               try {
            vr.view4(jTable1);
            
            
            
        stt = conn.prepareStatement("select * from subject where year = ? and  semester= ?  ");
        stt.setString(1, "2nd year");  
        stt.setString(2, "2nd semester"); 
    
    ResultSet rst = stt.executeQuery();
    jComboBoxsub.removeAllItems();
    while(rst.next())
    {
        maxID++;
        String subj=rst.getString("SUBJECT");
        jComboBoxsub.addItem(subj);
        
                
    }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
               
           }
           
       }
       if(jComboBoxyear.getSelectedItem().equals("3ed year"))
       {
           if(jComboBoxsem.getSelectedItem().equals("1st semester"))
           {
       
        try {
            vr.view5(jTable1);
            
            
             
        
        stt = conn.prepareStatement("select * from subject where year = ? and  semester= ?  ");
        stt.setString(1, "3ed year");  
        stt.setString(2, "1st semester"); 
    
    ResultSet rst = stt.executeQuery();
    jComboBoxsub.removeAllItems();
    while(rst.next())
    {
        maxID++;
        String subj=rst.getString("SUBJECT");
        jComboBoxsub.addItem(subj);
        
                
    }
            
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
           }
           else
           {
               try {
            vr.view6(jTable1);
            
            
              
        
        stt = conn.prepareStatement("select * from subject where year = ? and  semester= ?  ");
        stt.setString(1, "3ed year");  
        stt.setString(2, "2nd semester"); 
    
    ResultSet rst = stt.executeQuery();
    jComboBoxsub.removeAllItems();
    while(rst.next())
    {
        maxID++;
        String subj=rst.getString("SUBJECT");
        jComboBoxsub.addItem(subj);
        
                
    }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
               
           }
           
       }
       switch(maxID)
       {
           case 1:
               jTextFieldidno.setText("1");
               break;
           
           case 2:
               jTextFieldidno.setText("2");
               break;  
           
           case 3:
               jTextFieldidno.setText("3");
               break;
           
           case 4:
               jTextFieldidno.setText("4");
               break;  
           
           case 5:
               jTextFieldidno.setText("5");
               break;
           
           case 6:
               jTextFieldidno.setText("6");
               break;
           
           default:
               jTextFieldidno.setText("");
               break;    
       }
                       break;
                    default:JOptionPane.showMessageDialog(null,"Can not add more that 6 subjects per semester","Sorry",JOptionPane.ERROR_MESSAGE );   
                    
                     jTextFieldidno.setText("");
            jTextFieldcode.setText("");
            jTextFieldsub.setText("");
            jTextFieldno.setText("");
                }
               
                
            }
                
                
                
                
                
                
                
                
                
                
                } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
            
               
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButtonaddMouseClicked

    private void jButtonaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonaddActionPerformed

    private void jButtonupdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonupdateMouseClicked
        Connection2DB C=new Connection2DB();
        Connection conn=C.setconnection();
        Statement st=null;
        String id=jTextFieldcode.getText();
        String sub=jTextFieldsub.getText();
        String no=jTextFieldno.getText();
        String year=(String) jComboBoxyear.getSelectedItem();
        String sem=(String) jComboBoxsem.getSelectedItem();
        int log=0;
        int logs=0;
        
        
        try {
            st =(Statement)conn.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
           
        ResultSet rs=null;
        try {
            rs=st.executeQuery("SELECT * FROM SUBJECT");
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            while(rs.next())
            {
                if ( rs.getString("SUBJECT").equals(sub) || rs.getString("SUBJECT_CODE").equals(id))
                
                {
                    String sql;
                     sql="UPDATE SUBJECT SET SUBJECT_CODE = ? ,SUBJECT  = ?,ENROLL_NO = ?,YEAR= ?,SEMESTER = ? WHERE SUBJECT_CODE = ? OR SUBJECT= ?";
            PreparedStatement pst=conn.prepareStatement(sql);
            pst.setString(1, id);
            pst.setString(2,sub);
            pst.setString(3,no );
            pst.setString(4,year);
            pst.setString(5,sem);
            pst.setString(6,id);
            pst.setString(7,sub);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Subject updated","Successfull",JOptionPane.INFORMATION_MESSAGE );
            jTextFieldcode.setText("");
            jTextFieldsub.setText("");
            jTextFieldno.setText("");
            logs=1;
                    break;
                    
                }
                else
                {
                    
                 
                 log=1;   
                }
                
            }
            if (log==1)
            {if(logs==0)
            {
                
           
              
                JOptionPane.showMessageDialog(null,"Subject doesn't Exist","Can not add",JOptionPane.ERROR_MESSAGE );
            }   
            }


        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        {
            viewrecord vr=new viewrecord();
             if(jComboBoxyear.getSelectedItem().equals("1st year"))
       {
           if(jComboBoxsem.getSelectedItem().equals("1st semester"))
           {
        
        try {
            vr.view1(jTable1);
     
    
        
    
            
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         
           }
           else
           {
               try {
            vr.view2(jTable1);
            
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
               
           }
           
       }
       if(jComboBoxyear.getSelectedItem().equals("2nd year"))
       {
           if(jComboBoxsem.getSelectedItem().equals("1st semester"))
           {
       
        try {
            vr.view3(jTable1);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
           }
           else
           {
               try {
            vr.view4(jTable1);
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
               
           }
           
       }
       if(jComboBoxyear.getSelectedItem().equals("3ed year"))
       {
           if(jComboBoxsem.getSelectedItem().equals("1st semester"))
           {
       
        try {
            vr.view5(jTable1);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
           }
           else
           {
               try {
            vr.view6(jTable1);
           
            
            
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
               
           }
           
       }
            
            
        }


    }//GEN-LAST:event_jButtonupdateMouseClicked

    private void jButtonupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonupdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonupdateActionPerformed

    private void jTextFieldnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnoActionPerformed

    private void jTextFieldcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldcodeActionPerformed

    private void jTextFieldsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldsubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldsubActionPerformed

    private void jTextFieldidnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldidnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldidnoActionPerformed

    private void jButtondeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtondeleteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtondeleteMouseEntered

    private void jLabelsignoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsignoutMouseClicked
        // TODO add your handling code here:
        LogoutForm ltf=new LogoutForm();
        ltf.setVisible(true);
        ltf.pack();
        ltf.setLocationRelativeTo(null);//to make center on screen
        ltf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }//GEN-LAST:event_jLabelsignoutMouseClicked

    private void jLabelattendance3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelattendance3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelattendance3MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubjectForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButtonadd;
    private javax.swing.JButton jButtondelete;
    private javax.swing.JButton jButtongo;
    private javax.swing.JButton jButtonupdate;
    private javax.swing.JComboBox<String> jComboBoxsem;
    private javax.swing.JComboBox<String> jComboBoxsub;
    private javax.swing.JComboBox<String> jComboBoxyear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelabout;
    private javax.swing.JLabel jLabelabout1;
    private javax.swing.JLabel jLabelabout2;
    private javax.swing.JLabel jLabelattendance;
    private javax.swing.JLabel jLabelattendance3;
    private javax.swing.JLabel jLabellogin;
    private javax.swing.JLabel jLabeloverview;
    private javax.swing.JLabel jLabelsignout;
    private javax.swing.JLabel jLabelstudent;
    private javax.swing.JLabel jLabelsubject;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldcode;
    private javax.swing.JTextField jTextFieldidno;
    private javax.swing.JTextField jTextFieldno;
    private javax.swing.JTextField jTextFieldsub;
    private javax.swing.JLabel minimize;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent e) {
       Connection2DB C=new Connection2DB();
        
        Connection conn=C.setconnection();
        PreparedStatement st;    
        ResultSet rs=null;
        
        try {
            st = conn.prepareStatement("select * from login where login=? ");
            st.setString(1, "in");  
        
            rs = st.executeQuery(); 
            while(rs.next())
            {
             jLabellogin.setText(rs.getString("Firstname"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(DashboardForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void windowClosing(WindowEvent e) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowClosed(WindowEvent e) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowIconified(WindowEvent e) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowActivated(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
